apiVersion: v1
kind: Pod
metadata:
    name: my-pod-pv
spec:
    volumes:
        - name: pv-vol
          persistentVolumeClaim: 
            claimName: pv-claim
    containers:
        - name: my-pod
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: pv-vol