apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ns-dp
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx
        namespace: my-ns
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: nginx