apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: my-ds
spec:
  selector:
    matchLabels:
      app:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.22.1
          ports:
            - containerPort: 80
