apiversion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 6
  template:
    metadata:
      labels:
        app: nginx-node
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: nginx-node

---

apiVersion: v1
kind: NodePort
metadata:
  - name: nginx-nodeport
spec:
  type: NodePort
  selector:
    matchLabels:
      app: nginx-node
  ports:
    - name: http
      port:30002
      targetPort: 80
      nodePort: 30090