apiVersion: apps/v1

kind: Deployment

metadata:

  name: nginx-deployment-1

  labels:

    app: nginx

spec:

  replicas: 3

  selector:

    matchLabels:

      app: nginx-1

  template:

    metadata:

      labels:

        app: nginx-1

    spec:

      containers:

      - name: nginx

        image: nginx:1.14.2

        ports:

        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nodeport-dp
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      port: 30010
      targetPort: 80
      nodePort: 30100